In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 1. 데이터 오브젝트 생성하기
## 1) Series 
## 2) DataFrame

## 1) Series
serise는 1차원 배열 인덱스(값이 위치하고 있는 정보) 기준으로 데이터 저장, 인덱스는 따로 지정해주지 않는 한 기본적으로 1씩 증가하는 정수형

In [5]:
s=pd.Series([1,3,5,np.nan,6,8])

In [6]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [7]:
sr = pd.Series([17000, 18000, 1000, 5000],
       index=["피자", "치킨", "콜라", "맥주"])
print(sr)

피자    17000
치킨    18000
콜라     1000
맥주     5000
dtype: int64


In [8]:
print(sr.values)

[17000 18000  1000  5000]


In [9]:
print(sr.index)

Index(['피자', '치킨', '콜라', '맥주'], dtype='object')


## 2) DataFrame
데이터프레임은 2차원 리스트를 매개변수로 전달합니다. 
2차원이므로 행방향 인덱스(index)와 열방향 인덱스(column)가 존재합니다.
즉, 행과 열을 가지는 자료구조입니다. 시리즈가 인덱스(index)와 값(values)으로 구성된다면, 
데이터프레임은 열(columns)까지 추가되어 열(columns), 인덱스(index), 값(values)으로 구성됩니다.

In [10]:
values = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']

df = pd.DataFrame(values, index=index, columns=columns)
print(df)

       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9


In [11]:
print(df.index) # 인덱스 출력

Index(['one', 'two', 'three'], dtype='object')


In [12]:
print(df.columns) # 열 출력

Index(['A', 'B', 'C'], dtype='object')


In [13]:
print(df.values) # 값 출력

[[1 2 3]
 [4 5 6]
 [7 8 9]]


데이터프레임은 리스트(List), 시리즈(Series), 딕셔너리(dict), Numpy의 ndarrays, 또 다른 데이터프레임으로 생성할 수 있습니다. 


In [14]:
#리스트와 딕셔너리 이용
# 리스트로 생성하기
data = [
    ['1000', 'Steve', 90.72], 
    ['1001', 'James', 78.09], 
    ['1002', 'Doyeon', 98.43], 
    ['1003', 'Jane', 64.19], 
    ['1004', 'Pilwoong', 81.30],
    ['1005', 'Tony', 99.14],
]
df = pd.DataFrame(data)
print(df)

      0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [15]:
# 열 지정
df = pd.DataFrame(data, columns=['학번', '이름', '점수'])
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [16]:
# 딕셔너리로 생성하기
data = { '학번' : ['1000', '1001', '1002', '1003', '1004', '1005'],
'이름' : [ 'Steve', 'James', 'Doyeon', 'Jane', 'Pilwoong', 'Tony'],
         '점수': [90.72, 78.09, 98.43, 64.19, 81.30, 99.14]}

df = pd.DataFrame(data)
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


## 데이터 프레임 조회하기

In [17]:
print(df.head(3)) # 앞 부분을 3개만 보기

     학번      이름     점수
0  1000   Steve  90.72
1  1001   James  78.09
2  1002  Doyeon  98.43


In [18]:
print(df['학번']) # '학번'에 해당되는 열을 보기

0    1000
1    1001
2    1002
3    1003
4    1004
5    1005
Name: 학번, dtype: object


In [19]:
print(df.index)

RangeIndex(start=0, stop=6, step=1)


In [20]:
# 하루씩 카운트해서 년도 월일로 날짜 만들 수 있다!!!
dates = pd.date_range('20130101', periods=6)


In [21]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [34]:
df2=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("ABCD"))

# numpy를 이용한 난수 생성
### 표준 정규분포 난수
np.random.randn(a)->a개 생성
np.random.randn(a,b)->a,b 매트릭스 생성
### 균일분포의 정수 난수 1개생성
np.random.randint(a)-> 0부터 a 까지 랜덤한 숫자 1개
np.random.randint(a,b)-> a부터 b까지 랜덤숫자 1개

### 0~1 사이의 균일분포
np.random.rand(a)-> a개 생성
np.random.rand(a,b)->a,b 매트릭스 생성

### 기존 데이터 순서 바꿈
np.random.shuffle()
### 기존 데이터에서 샘플링
np.random.choice()
### 중복된 값 제거하고 리스트로 출력
np.unique()
### 발생하지 않는 사건에 대해서 카운트 
np.bincount()


In [32]:
np.random.randint(3,34)

20

In [35]:
df2

A         B         C         D
2013-01-01  0.542586 -0.705189  2.393410  0.369052
2013-01-02  0.701094  1.473984 -0.168700 -0.184383
2013-01-03  0.813165 -0.201787  1.098712 -0.556822
2013-01-04  1.166572 -0.291975 -0.797199 -0.711614
2013-01-05 -0.387502  0.849923 -0.794000 -2.044858
2013-01-06 -0.824612  1.209726 -0.395022  1.336559

In [36]:
# 통계 속성들 보여줌!!
df2.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.335217  0.389114  0.222867 -0.298678
std    0.769932  0.902578  1.271851  1.133069
min   -0.824612 -0.705189 -0.797199 -2.044858
25%   -0.154980 -0.269428 -0.694256 -0.672916
50%    0.621840  0.324068 -0.281861 -0.370602
75%    0.785147  1.119776  0.781859  0.230693
max    1.166572  1.473984  2.393410  1.336559

In [38]:
# transpose : a -> a.T
df2.T

2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.542586    0.701094    0.813165    1.166572   -0.387502   -0.824612
B   -0.705189    1.473984   -0.201787   -0.291975    0.849923    1.209726
C    2.393410   -0.168700    1.098712   -0.797199   -0.794000   -0.395022
D    0.369052   -0.184383   -0.556822   -0.711614   -2.044858    1.336559

In [42]:
# axis=0-> 기본값 인덱스를 기준으로 정렬, axis=1 -> 컬럼을 기준으로 정렬  
# ascending=True->오름차순 정렬  ascending=False-> 내림차순 정렬
df2.sort_index(axis=1,ascending=False)

D         C         B         A
2013-01-01  0.369052  2.393410 -0.705189  0.542586
2013-01-02 -0.184383 -0.168700  1.473984  0.701094
2013-01-03 -0.556822  1.098712 -0.201787  0.813165
2013-01-04 -0.711614 -0.797199 -0.291975  1.166572
2013-01-05 -2.044858 -0.794000  0.849923 -0.387502
2013-01-06  1.336559 -0.395022  1.209726 -0.824612

In [44]:
# 열가져오기
df2['A']

2013-01-01    0.542586
2013-01-02    0.701094
2013-01-03    0.813165
2013-01-04    1.166572
2013-01-05   -0.387502
2013-01-06   -0.824612
Freq: D, Name: A, dtype: float64

In [43]:
# 행 가져오기
df2[1:3]

A         B         C         D
2013-01-02  0.701094  1.473984 -0.168700 -0.184383
2013-01-03  0.813165 -0.201787  1.098712 -0.556822

In [45]:
# 행, 열 인덱싱
df2[1:3]['A']

2013-01-02    0.701094
2013-01-03    0.813165
Freq: D, Name: A, dtype: float64

## .loc 이용->이름으로 긁어오기

In [47]:
df2.loc[dates[0]]

A    0.542586
B   -0.705189
C    2.393410
D    0.369052
Name: 2013-01-01 00:00:00, dtype: float64

In [49]:
df2.loc['20130101']

A    0.542586
B   -0.705189
C    2.393410
D    0.369052
Name: 2013-01-01 00:00:00, dtype: float64

In [50]:
df2.loc['2013-01-01']

A    0.542586
B   -0.705189
C    2.393410
D    0.369052
Name: 2013-01-01 00:00:00, dtype: float64

In [51]:
df2.loc[:,['A','B']]

A         B
2013-01-01  0.542586 -0.705189
2013-01-02  0.701094  1.473984
2013-01-03  0.813165 -0.201787
2013-01-04  1.166572 -0.291975
2013-01-05 -0.387502  0.849923
2013-01-06 -0.824612  1.209726

##  .iloc ->위치를 이용하여 선택하기

In [52]:
# 2행 위치의 것 가져오기
df2.iloc[2]

A    0.813165
B   -0.201787
C    1.098712
D   -0.556822
Name: 2013-01-03 00:00:00, dtype: float64

In [53]:
# 3,4 행, 0,1 열 
df2.iloc[3:5,0:2]

A         B
2013-01-04  1.166572 -0.291975
2013-01-05 -0.387502  0.849923

In [54]:
# 1,2,4 행, 1,2 열
df2.iloc[[1,2,4],[0,2]]

A         C
2013-01-02  0.701094 -0.168700
2013-01-03  0.813165  1.098712
2013-01-05 -0.387502 -0.794000